#!/usr/bin/env bash
# sustainability.ai — one-shot launcher.
# Builds every image from local source (so local changes such as branding are
# included), starts the full Docker stack, waits until it is healthy, and opens
# the browser.
#
# Usage:
#   ./start.sh            Build (if needed) and start everything
#   ./start.sh --rebuild  Force a fresh rebuild of the local images, then start
#   ./start.sh stop       Stop everything
#   ./start.sh restart    Stop, then start
#   ./start.sh logs       Follow logs (Ctrl+C to exit)
#   ./start.sh status     Show container status
#
# Extra profiles (e.g. qdrant, minio, neo4j, searxng) can be added with
#   COMPOSE_PROFILES=qdrant,minio ./start.sh
# Langfuse is enabled automatically when LANGFUSE_PUBLIC_KEY is set in .env.

set -euo pipefail

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { printf "%b\n" "${BLUE}[INFO]${NC} $*"; }
ok()      { printf "%b\n" "${GREEN}[OK]${NC} $*"; }
warn()    { printf "%b\n" "${YELLOW}[WARN]${NC} $*"; }
die()     { printf "%b\n" "${RED}[ERROR]${NC} $*" >&2; exit 1; }

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

# Services built from this repo (everything else is a public upstream image).
LOCAL_SERVICES=(frontend app docreader)

# ---------- preflight ----------
command -v docker >/dev/null 2>&1 || die "Docker is not installed. Install Docker Desktop first."
docker info >/dev/null 2>&1       || die "Docker is not running. Start Docker Desktop and try again."
if docker compose version >/dev/null 2>&1; then
    COMPOSE=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE=(docker-compose)
else
    die "Docker Compose not found."
fi

if [ ! -f .env ]; then
    [ -f .env.example ] || die ".env and .env.example are both missing."
    cp .env.example .env
    warn "Created .env from .env.example — review it (models, passwords) before production use."
fi

# Read a single key from .env without sourcing the whole file (tolerates CRLF).
env_get() { grep -E "^$1=" .env 2>/dev/null | tail -n1 | cut -d= -f2- | tr -d '\r' | sed -e 's/^"//' -e 's/"$//'; }

FRONTEND_PORT="$(env_get FRONTEND_PORT)"; FRONTEND_PORT="${FRONTEND_PORT:-80}"
APP_PORT="$(env_get APP_PORT)";           APP_PORT="${APP_PORT:-8080}"

profiles="${COMPOSE_PROFILES:-}"
if [ -n "$(env_get LANGFUSE_PUBLIC_KEY)" ] && [[ ",$profiles," != *",langfuse,"* ]]; then
    profiles="${profiles:+$profiles,}langfuse"
fi
export COMPOSE_PROFILES="$profiles"
export VITE_FRONTEND_COMMIT="${VITE_FRONTEND_COMMIT:-local-$(date +%Y%m%d%H%M)}"

# docker-compose.yml names our images ORG_PLACEHOLDER/..., which Docker rejects
# (repository names must be lowercase). Give the locally built images valid
# names via an override file instead of editing docker-compose.yml.
LOCAL_IMAGE_NS="${LOCAL_IMAGE_NS:-sustainability-ai}"
OVERRIDE_FILE="docker-compose.local.yml"
cat > "$OVERRIDE_FILE" <<EOF
# Generated by start.sh — do not edit; changes are overwritten on every run.
services:
  frontend:
    image: ${LOCAL_IMAGE_NS}/enterpriserag-ui:local
  app:
    image: ${LOCAL_IMAGE_NS}/enterpriserag-app:local
  docreader:
    image: ${LOCAL_IMAGE_NS}/enterpriserag-docreader:local
  sandbox:
    image: ${LOCAL_IMAGE_NS}/enterpriserag-sandbox:local
EOF

compose() { "${COMPOSE[@]}" -f docker-compose.yml -f "$OVERRIDE_FILE" "$@"; }

# ---------- helpers ----------
port_busy() {
    # true if something other than our own containers is listening on the port
    local port=$1
    if docker ps --format '{{.Names}} {{.Ports}}' | grep -E "EnterpriseRag-" | grep -q ":${port}->"; then
        return 1
    fi
    if command -v netstat >/dev/null 2>&1; then
        netstat -an 2>/dev/null | grep -Eq "[:.]${port}[[:space:]].*LISTEN"
    else
        return 1
    fi
}

open_browser() {
    local url=$1
    case "$(uname -s)" in
        MINGW*|MSYS*|CYGWIN*) cmd.exe /c start "" "$url" >/dev/null 2>&1 || true ;;
        Darwin)               open "$url" >/dev/null 2>&1 || true ;;
        *)                    command -v xdg-open >/dev/null 2>&1 && xdg-open "$url" >/dev/null 2>&1 || true ;;
    esac
}

wait_healthy() {
    local url=$1 max=${2:-300} waited=0
    info "Waiting for the app to become healthy (up to ${max}s)..."
    until curl -fsS -o /dev/null "$url" 2>/dev/null; do
        if [ "$waited" -ge "$max" ]; then
            warn "Not healthy after ${max}s. Check logs with: ./start.sh logs"
            return 1
        fi
        # Bail out early if the app container crashed.
        if [ "$(docker inspect -f '{{.State.Status}}' EnterpriseRag-app 2>/dev/null || echo missing)" = "exited" ]; then
            compose logs --tail=40 app || true
            die "The app container exited. See the logs above."
        fi
        sleep 5; waited=$((waited + 5))
        printf "."
    done
    printf "\n"
}

start() {
    local force_build=${1:-0}

    for p in "$FRONTEND_PORT" "$APP_PORT"; do
        if port_busy "$p"; then
            die "Port $p is already in use by another program. Free it or change it in .env (FRONTEND_PORT / APP_PORT)."
        fi
    done

    info "Profiles: ${COMPOSE_PROFILES:-<none>}"

    # `config --images` also lists dependencies, so keep only this repo's images.
    local missing=0 img
    while read -r img; do
        [ -n "$img" ] || continue
        docker image inspect "$img" >/dev/null 2>&1 || missing=1
    done < <(compose config --images "${LOCAL_SERVICES[@]}" 2>/dev/null | grep -i "/enterpriserag-" || true)

    if [ "$force_build" = 1 ] || [ "$missing" = 1 ]; then
        info "Building local images: ${LOCAL_SERVICES[*]} (the first build can take 10-20 minutes)..."
        compose build "${LOCAL_SERVICES[@]}"
    else
        info "Local images already built (use --rebuild after code changes)."
    fi

    info "Pulling upstream images (postgres, redis, ...)..."
    compose pull --ignore-buildable --quiet 2>/dev/null \
        || compose pull --ignore-pull-failures --quiet 2>/dev/null \
        || warn "Some images could not be pulled; continuing with what is available."

    info "Starting containers..."
    compose up -d --no-build

    if command -v curl >/dev/null 2>&1; then
        wait_healthy "http://localhost:${APP_PORT}/health" 300 || true
    fi

    local url="http://localhost"
    [ "$FRONTEND_PORT" != "80" ] && url="${url}:${FRONTEND_PORT}"

    echo
    ok "sustainability.ai is running"
    echo "  Web UI:   $url"
    echo "  API:      http://localhost:${APP_PORT}"
    echo "  Logs:     ./start.sh logs"
    echo "  Stop:     ./start.sh stop"
    echo
    open_browser "$url"
}

stop() {
    info "Stopping all services..."
    # Include every profile so optional services are stopped too.
    COMPOSE_PROFILES="*" compose down
    ok "Stopped."
}

# ---------- entry ----------
case "${1:-start}" in
    start|"")        start 0 ;;
    --rebuild|rebuild) start 1 ;;
    stop)            stop ;;
    restart)         stop; start 0 ;;
    logs)            compose logs -f --tail=100 ;;
    status|ps)       compose ps ;;
    -h|--help|help)  sed -n '2,17p' "$0" | sed 's/^# \{0,1\}//' ;;
    *)               die "Unknown command: $1 (try ./start.sh --help)" ;;
esac
