/**
 * Copy for the spotlight product tours.
 *
 * SpotlightGuide addresses a step by path (`<prefix>.<step key>.title|desc`), so
 * the strings stay keyed rather than inlined into each guide definition. Every
 * `stepI18nPrefix` in `contextualGuides.ts` must have matching entries here.
 */
export const GUIDE_COPY: Record<string, string> = {
  'newUserGuide.stepOf': '{current} / {total}',
  'newUserGuide.skip': 'Skip',
  'newUserGuide.prev': 'Back',
  'newUserGuide.next': 'Next',
  'newUserGuide.done': 'Done',
  'newUserGuide.reopen': 'Product tour',
  'newUserGuide.steps.welcome.title': 'Welcome to sustainability.ai',
  'newUserGuide.steps.welcome.desc': 'A few quick steps to get you familiar with knowledge bases, chat and agents. Click "Next" to begin.',
  'newUserGuide.steps.knowledge.title': 'Create your knowledge base',
  'newUserGuide.steps.knowledge.desc': 'Everything starts here: upload documents, web pages or FAQs and sustainability.ai parses and indexes them automatically. Click here to open knowledge bases.',
  'newUserGuide.steps.chat.title': 'Start an AI chat',
  'newUserGuide.steps.chat.desc': 'Ask questions grounded in your knowledge base and get accurate answers with cited sources. Click here to start a new chat.',
  'newUserGuide.steps.agents.title': 'Build dedicated agents',
  'newUserGuide.steps.agents.desc': 'Combine knowledge bases, prompts and tools into reusable agents that capture your expertise.',
  'newUserGuide.steps.settings.title': 'Account & settings',
  'newUserGuide.steps.settings.desc': 'Open this to manage your account, members and system settings. You can reopen this tour from the help button next to your name at the top of this menu.',
  'newUserGuide.steps.models.title': 'Configure your models',
  'newUserGuide.steps.models.desc': 'A key step: add chat, embedding and other models in Model Management so knowledge bases and chat can work. Click "Add model" to get started.',
  'newUserGuide.steps.done.title': 'You are all set',
  'newUserGuide.steps.done.desc': 'You now know the essentials — start building your knowledge assistant! Revisit this tour anytime from the help button next to your name in this menu.',
  'contextualGuide.stepOf': '{current} / {total}',
  'contextualGuide.skip': 'Skip',
  'contextualGuide.prev': 'Back',
  'contextualGuide.next': 'Next',
  'contextualGuide.done': 'Got it',
  'contextualGuide.interactHint': 'Click the highlighted area to continue',
  'contextualGuide.kbList.steps.create.title': 'Create your first knowledge base',
  'contextualGuide.kbList.steps.create.desc': 'Knowledge bases hold documents and FAQs. Click the highlighted "New knowledge base" button below and we will walk you through the form.',
  'contextualGuide.tenantModels.needChatModelFirst': 'Add a chat model (KnowledgeQA) before creating an agent.',
  'contextualGuide.tenantModels.steps.intro.title': 'Configure models first',
  'contextualGuide.tenantModels.steps.intro.desc': 'A document knowledge base needs at least one chat model (summaries and Q&A) and one Embedding model (vector search). Add them in system settings.',
  'contextualGuide.tenantModels.steps.addModel.title': 'Add models',
  'contextualGuide.tenantModels.steps.addModel.desc': 'Click "Add model" and configure KnowledgeQA (chat) and Embedding types. Lite users can pull local models via Ollama.',
  'contextualGuide.tenantModels.steps.done.title': 'Then continue',
  'contextualGuide.tenantModels.steps.done.desc': 'After saving models, close settings and click "New knowledge base". The wizard will walk you through type, indexing, and model binding.',
  'contextualGuide.tenantModels.stepsAgent.intro.title': 'Configure a chat model first',
  'contextualGuide.tenantModels.stepsAgent.intro.desc': 'Creating an agent requires at least one KnowledgeQA model. Add it in system settings (Embedding is only required for knowledge bases).',
  'contextualGuide.tenantModels.stepsAgent.addModel.title': 'Add a chat model',
  'contextualGuide.tenantModels.stepsAgent.addModel.desc': 'Click "Add model" and configure a KnowledgeQA type.',
  'contextualGuide.tenantModels.stepsAgent.done.title': 'Then create an agent',
  'contextualGuide.tenantModels.stepsAgent.done.desc': 'After saving, close settings and click "Create agent". The wizard covers mode, knowledge bases, and attachment upload options.',
  'contextualGuide.kbCreate.steps.type.title': 'Choose a type',
  'contextualGuide.kbCreate.steps.type.desc': 'Document bases are for PDFs, Word files, and similar uploads. FAQ bases are for question–answer pairs. The type cannot be changed later.',
  'contextualGuide.kbCreate.steps.name.title': 'Enter a name',
  'contextualGuide.kbCreate.steps.name.desc': 'Pick a clear name such as "Product manual" or "Support FAQ". Description is optional.',
  'contextualGuide.kbCreate.steps.indexing.title': 'Indexing capabilities',
  'contextualGuide.kbCreate.steps.indexing.desc': 'Vector and keyword search are on by default. You can also enable Wiki or knowledge-graph indexing. Keep at least one search mode enabled.',
  'contextualGuide.kbCreate.steps.navModels.title': 'Model setup (required)',
  'contextualGuide.kbCreate.steps.navModels.desc': 'Every knowledge base needs a chat model; retrieval also requires an Embedding model. Open "Model configuration" on the left.',
  'contextualGuide.kbCreate.steps.llm.title': 'Chat / summary model',
  'contextualGuide.kbCreate.steps.llm.desc': 'Used for summaries and answers. If the list is empty, use the dropdown to open settings and add a model.',
  'contextualGuide.kbCreate.steps.embedding.title': 'Embedding model',
  'contextualGuide.kbCreate.steps.embedding.desc': 'Turns text into vectors for semantic search. Works with vector/keyword indexing above.',
  'contextualGuide.kbCreate.steps.parser.title': 'Parser engine (optional)',
  'contextualGuide.kbCreate.steps.parser.desc': 'How PDFs and Office files are parsed. Defaults work for most cases; adjust if you need OCR or special layouts.',
  'contextualGuide.kbCreate.steps.chunking.title': 'Chunking (optional)',
  'contextualGuide.kbCreate.steps.chunking.desc': 'How documents are split for retrieval. Default chunk sizes are tuned for RAG and rarely need changes.',
  'contextualGuide.kbCreate.steps.storage.title': 'Storage (optional)',
  'contextualGuide.kbCreate.steps.storage.desc': 'Where raw files are stored (local or object storage). The workspace default is usually fine.',
  'contextualGuide.kbCreate.steps.navMultimodal.title': 'Multimodal / images (optional)',
  'contextualGuide.kbCreate.steps.navMultimodal.desc': 'Enable this if documents contain charts, scans, or image-heavy content that needs vision understanding.',
  'contextualGuide.kbCreate.steps.multimodalToggle.title': 'Enable multimodal parsing',
  'contextualGuide.kbCreate.steps.multimodalToggle.desc': 'When on, image-bearing uploads are processed with a vision-language model for better retrieval.',
  'contextualGuide.kbCreate.steps.multimodalVllm.title': 'Choose a VLM model',
  'contextualGuide.kbCreate.steps.multimodalVllm.desc': 'Multimodal requires a VLM. Add one in system settings if the list is empty.',
  'contextualGuide.kbCreate.steps.faq.title': 'FAQ indexing',
  'contextualGuide.kbCreate.steps.faq.desc': 'Choose how Q&A pairs are indexed. You can add FAQ entries after creation.',
  'contextualGuide.kbCreate.steps.submit.title': 'Create the knowledge base',
  'contextualGuide.kbCreate.steps.submit.desc': 'Click Got it to finish the guide without creating a knowledge base. When ready, enter a name, confirm the type and models, then click Create.',
  'contextualGuide.agentList.steps.create.title': 'Create your agent',
  'contextualGuide.agentList.steps.create.desc': 'Agents combine models, knowledge bases, tools, and prompts into reusable assistants. Click the highlighted "Create agent" button.',
  'contextualGuide.agentCreate.steps.mode.title': 'Choose run mode',
  'contextualGuide.agentCreate.steps.mode.desc': '"Quick answer" for straightforward Q&A; "Smart reasoning" uses tools and multi-step thinking for complex tasks.',
  'contextualGuide.agentCreate.steps.agentType.title': 'Choose an agent type',
  'contextualGuide.agentCreate.steps.agentType.desc': 'Presets fill in the system prompt, recommended tools, and knowledge scope (e.g. Wiki builder, data analysis). Switch by scenario—name and description update accordingly.',
  'contextualGuide.agentCreate.steps.name.title': 'Name and description',
  'contextualGuide.agentCreate.steps.name.desc': 'Pick a recognizable name. Smart-reasoning mode may pre-fill a default you can edit.',
  'contextualGuide.agentCreate.steps.navModel.title': 'Bind a chat model',
  'contextualGuide.agentCreate.steps.navModel.desc': 'Every agent needs a KnowledgeQA model as its reasoning engine.',
  'contextualGuide.agentCreate.steps.model.title': 'Select model',
  'contextualGuide.agentCreate.steps.model.desc': 'Choose from configured chat models, or add one in system settings first.',
  'contextualGuide.agentCreate.steps.navKnowledge.title': 'Link knowledge bases',
  'contextualGuide.agentCreate.steps.navKnowledge.desc': 'Control which knowledge the agent can retrieve. Default is all knowledge bases.',
  'contextualGuide.agentCreate.steps.knowledge.title': 'Knowledge scope',
  'contextualGuide.agentCreate.steps.knowledge.desc': '"All" for general assistants; "Selected" for a domain; "None" relies on the model alone or web search.',
  'contextualGuide.agentCreate.steps.navWebsearch.title': 'Web search (optional)',
  'contextualGuide.agentCreate.steps.navWebsearch.desc': 'Allow the agent to call external search for up-to-date information.',
  'contextualGuide.agentCreate.steps.navMultimodal.title': 'Attachment upload (optional)',
  'contextualGuide.agentCreate.steps.navMultimodal.desc': 'Lets users send images, documents, and audio in chat; image understanding requires a VLM in system settings.',
  'contextualGuide.agentCreate.steps.multimodal.title': 'Enable attachment upload',
  'contextualGuide.agentCreate.steps.multimodal.desc': 'Configure image and audio upload plus attachment parse rules; select a VLM below when image upload is enabled.',
  'contextualGuide.agentCreate.steps.navTools.title': 'Tools & MCP (optional)',
  'contextualGuide.agentCreate.steps.navTools.desc': 'In smart-reasoning mode, enable built-in tools and MCP services for search, code, and more.',
  'contextualGuide.agentCreate.steps.submit.title': 'Save the agent',
  'contextualGuide.agentCreate.steps.submit.desc': 'Click the highlighted confirm button to finish. You can then select this agent in chat.',
  'contextualGuide.kbDetail.steps.intro.title': 'This knowledge base is empty',
  'contextualGuide.kbDetail.steps.intro.desc': 'Add your first item so you can search and chat over it. You can also drag and drop supported file types.',
  'contextualGuide.kbDetail.steps.upload.title': 'Add documents',
  'contextualGuide.kbDetail.steps.upload.desc': 'Use this menu to upload files or folders, import a URL, or create content online.',
  'contextualGuide.kbDetail.steps.done.title': 'Ready after parsing',
  'contextualGuide.kbDetail.steps.done.desc': 'Once documents are indexed, mention this knowledge base in chat with {\'@\'} to get answers with citations.',
  'contextualGuide.chat.steps.kb.title': 'Choose knowledge scope',
  'contextualGuide.chat.steps.kb.desc': 'Click {\'@\'} to pick one or more knowledge bases or files. Answers use only the selection; otherwise the current agent settings apply.',
  'contextualGuide.chat.steps.input.title': 'Type your question',
  'contextualGuide.chat.steps.input.desc': 'Describe what you want to know, or click a suggested question above to get started quickly.',
  'contextualGuide.chat.steps.send.title': 'Send to start chatting',
  'contextualGuide.chat.steps.send.desc': 'Sending creates a new session. The AI answers using your knowledge base and shows cited passages.',
  'contextualGuide.chat.steps.done.title': 'You are ready to explore',
  'contextualGuide.chat.steps.done.desc': 'Try a question related to your uploaded documents and see grounded answers with references.',
}

/** Copy for a guide path; an unregistered path renders as empty rather than raw. */
export function guideText(path: string): string {
  return GUIDE_COPY[path] ?? ''
}
