#!/usr/bin/env bash
set -euo pipefail

#
# Build and package the EnterpriseRag macOS desktop app (.app) locally
#
# Usage:
#   ./scripts/package-mac-app.sh
#   SKIP_FRONTEND=1 ./scripts/package-mac-app.sh  # skip the frontend build
#

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${ROOT_DIR}"

APP_NAME="EnterpriseRag Lite"
APP_BUNDLE="${APP_NAME}.app"
DIST_DIR="dist/${APP_BUNDLE}"

echo "=== EnterpriseRag Mac App Packager ==="
echo "  Output: dist/${APP_BUNDLE}"
echo ""

# ── Step 1: Build frontend (if not skipped) ──
if [ "${SKIP_FRONTEND:-}" != "1" ]; then
    if [ -f frontend/package.json ]; then
        echo ">> Building frontend..."
        (cd frontend && npm ci --prefer-offline && npm run build)
        # The Lite backend serves the SPA from ./web (see serveFrontendStatic in internal/router), so, as in package-lite.sh, web must be refreshed from dist
        echo ">> Sync frontend/dist -> web/"
        rm -rf web
        cp -r frontend/dist web
    else
        echo ">> No frontend/package.json found, skipping frontend build"
    fi
fi

if [ ! -f web/index.html ]; then
    echo "WARNING: web/index.html not found. The Lite desktop app serves the frontend from Resources/web; build the frontend fully first (do not use SKIP_FRONTEND), or run: cp -r frontend/dist web"
fi

# ── Step 2: Build with Wails ──
echo ">> Building Wails Desktop App..."

# Prompt the user to install the wails CLI if it is missing
if ! command -v wails >/dev/null 2>&1; then
    echo "Wails CLI not found. Please install it first:"
    echo "go install github.com/wailsapp/wails/v2/cmd/wails@latest"
    exit 1
fi

# Package with Wails (the dependency proxy must be configured first)
export GONOSUMDB="git.sr.ht/*"
export GOPROXY="https://goproxy.cn,direct"
export CGO_CFLAGS="-Wno-deprecated-declarations"
export CGO_LDFLAGS="-Wl,-no_warn_duplicate_libraries"
export EDITION=lite

# The generated gRPC code for Milvus and Qdrant both register a descriptor named "common.proto", which clashes within a single process.
# -ldflags -X conflictPolicy=warn only applies to the final link and cannot cover the separate go subprocess Wails spawns to generate bindings.
# The upstream guidance is at https://protobuf.dev/reference/go/faq#namespace-conflict
export GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn

# Read the version number and set up LDFLAGS
eval "$(./scripts/get_version.sh env)"
LDFLAGS="$(./scripts/get_version.sh ldflags) -X 'google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn'"

# Wails bindings are generated by default (for window.go.main.App.* and similar); with -skipbindings, __ENTERPRISERAG_API_BASE__ must be injected in OnDomReady instead
(cd cmd/desktop && wails build -clean -tags "sqlite_fts5" -ldflags="$LDFLAGS" -o "${APP_NAME}")

# ── Step 3: Copy generated .app to dist ──
echo ">> Assembling package..."
mkdir -p dist
rm -rf "${DIST_DIR}"
cp -R "cmd/desktop/build/bin/${APP_BUNDLE}" "dist/"

# Copy the configuration files and the initial database migration scripts into the .app resources
RESOURCES_DIR="${DIST_DIR}/Contents/Resources"
mkdir -p "${RESOURCES_DIR}/config"
mkdir -p "${RESOURCES_DIR}/migrations/sqlite"
bash ./scripts/copy-licenses.sh "${RESOURCES_DIR}"

if [ -f .env.lite.example ]; then
    cp .env.lite.example "${RESOURCES_DIR}/.env"
fi
if [ -d migrations/sqlite ]; then
    cp -r migrations/sqlite/* "${RESOURCES_DIR}/migrations/sqlite/"
fi
if [ -d config ]; then
    cp -r config/* "${RESOURCES_DIR}/config/"
fi
if [ -d web ]; then
    cp -r web "${RESOURCES_DIR}/"
fi

# Note: the binary produced by wails build defaults to the app's Contents/MacOS directory as its working directory,
# so the configuration file path handling in the code may need adjusting later.

echo ""
echo "=== Done ==="
echo "  App generated at: dist/${APP_BUNDLE}"
echo "  You can double click it to run!"
